import{a as S,S as v,i}from"./assets/vendor-VVWBAj3V.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const w="55520229-6b38dd18315a985816c1e4a23",M="https://pixabay.com/api/",u=15;async function m(s,e=1){const{data:o}=await S(M,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:e}});return o.total_pages=Math.floor(o.totalHits/u),o}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".btn-load-more"),q=new v(".gallery-item a",{captionDelay:1e3,captionsData:"alt"});function g(s){const e=s.map(o=>`
          <li class="gallery-item">
          <a class="gallery-thumb" href="${o.largeImageURL}"><img class="gallery-img" src="${o.webformatURL}" alt="${o.name||o.tags}" /></a>
          <ul class="gallery-content-list">
            <li class="gallery-content-item"><span>Likes</span><span>${o.likes}</span></li>
            <li class="gallery-content-item"><span>Views</span><span>${o.views}</span></li>
            <li class="gallery-content-item"><span>Comments</span><span>${o.comments}</span></li>
            <li class="gallery-content-item"><span>Downloads</span><span>${o.downloads}</span></li>
          </ul>
      </li>`).join("");p.insertAdjacentHTML("beforeend",e),q.refresh()}function $(){p.innerHTML=""}function h(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}function x(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}const B=document.querySelector(".form");document.querySelector(".gallery");const n=document.querySelector(".btn-load-more");let l="",a=1;i.settings({pauseOnHover:!0,position:"topRight"});B.addEventListener("submit",O);n.addEventListener("click",P);async function O(s){if(s.preventDefault(),l=s.target.elements["search-text"].value,$(),b(),a=1,l!==""){h();try{const e=await m(l,a);if(!e.hits.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),a<e.total_pages&&x()}catch(e){i.error({message:e.message})}finally{L()}}}async function P(s){a+=1,h(),n.disabled=!0,n.textContent="Loading...";try{const e=await m(l,a);g(e.hits),a>=e.total_pages&&(b(),i.info({message:"We're sorry, but you've reached the end of search results."})),_()}catch(e){i.error({message:e.message})}finally{L(),n.disabled=!1,n.textContent="Load more"}}function _(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;scrollBy({top:Math.round((e+24)*2),behavior:"smooth"})}
//# sourceMappingURL=index.js.map
